# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\"!\n\x10UserCheckRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"4\n\x11UserCheckResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"?\n\x1b\x44\x65leteUserInterestsResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x0bUserService\x12:\n\x11\x43heckIfUserExists\x12\x11.UserCheckRequest\x1a\x12.UserCheckResponse2U\n\x0b\x44\x61taService\x12\x46\n\x13\x44\x65leteUserInterests\x12\x11.UserCheckRequest\x1a\x1c.DeleteUserInterestsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCHECKREQUEST']._serialized_start=22
  _globals['_USERCHECKREQUEST']._serialized_end=55
  _globals['_USERCHECKRESPONSE']._serialized_start=57
  _globals['_USERCHECKRESPONSE']._serialized_end=109
  _globals['_DELETEUSERINTERESTSRESPONSE']._serialized_start=111
  _globals['_DELETEUSERINTERESTSRESPONSE']._serialized_end=174
  _globals['_USERSERVICE']._serialized_start=176
  _globals['_USERSERVICE']._serialized_end=249
  _globals['_DATASERVICE']._serialized_start=251
  _globals['_DATASERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
